name: Zig Test
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - "re.zig"
    - "thirdparty/*"
    - "build.zig"
    - ".github/**/*.yml"
  pull_request:

jobs:
  zig-test:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')" # manually skip ci through commit message

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo snap install zig --classic --beta
    - name: Run Tests
      run: zig build test
