name: Zig Test
on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - "re.zig"
    - "thirdparty/*"
    - "build.zig"
    - ".github/**/*.yml"
  pull_request:

jobs:
  zig-test:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-ci')" # manually skip ci through commit message

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
           sudo snap install zig --classic --beta
           pip install meson ninja
    - name: Debug CI
      run: |
           meson --help
           meson setup thirdparty/fadec/build thirdparty/fadec
    - name: Run Tests
      run: zig build test
